version: '3'

services:
  backend:
    build: backEnd/
    depends_on:
      - 'database'
    ports: 
      - '8080:8080'

    command: "npx knex migrate:latest && npx knex seed:run && npm start"

  frontend:
    build: frontend/
    depends_on:
      - 'backend'
    ports:
      - '3000:3000'

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    

# works below 


# version: '3.1'
# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: postgres

#   client:
#     build: client/
#     volumes:
#       - /Users/mbp19/Desktop/galvanize/docker-checkpoint/client/:/src/app
#     depends_on: 
#       - db
#     ports:
#       - 3000:3000
    
#   server: 
#     build: server/
#     volumes:
#       - /Users/mbp19/Desktop/galvanize/docker-checkpoint/server/:/src/app
#     depends_on:
#       - db
#     ports:
#       - 8080:8080
#     command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start" 